apiVersion: v1
kind: ConfigMap
metadata:
  name: kmux
data:
  config.yaml: |-
    kmux:
      sink:
        stream: pulsar

    pulsar:
      servers:
        - "localhost:6650"
      topic-prefix: persistent://public/default/
      encryption:
        # TLS
        enable: false
        ca-cert: /var/run/kmux/ca-cert.pem 
      auth:
        # mTLS
        # `encryption` should be enabled and configured to use `auth`.
        enable: false
        cert: /var/run/kmux/cert.pem
        key: /var/run/kmux/key.pem