kmux:
  sink:
    database: mongodb
  # If HashiCorp Vault is used for storing database secrets
  # vault: hashiVault

vault:
  server: "http://vault:8200"

database:
  name: accuknox
  server: "127.0.0.1:27017"
  username: ""
  password: ""
  # If Vault is used for storing database secrets 
  # vault:
  #   secretPath: "/knox/microservice/secrets"
  #   key:
  #     username: "mongo_user"
  #     password: "mongo_password"