name: PR Checks

on:
  pull_request_target:
    branches:
      - '*'

jobs:
  go-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: v1.18

      - name: Pull the dependencies
        env:
          USER: knoxuser
          TOKEN: ${{ secrets.AK_PAT_REPO_SCOPE }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
          go env -w GOPRIVATE=github.com/accuknox
          go mod download
          git config --global --remove-section url."https://${USER}:${TOKEN}@github.com"

      - name: build
        run: make

      - name: go-fmt
        run: make fmt

      - name: go-lint
        uses: morphy2k/revive-action@v2

      - name: go-sec
        run: make sec
